! Fortran subroutine for calculating Laplacian on a grid
! Compile (wrap) with:
! $ f2py -c --fcompiler=gnu95 -m laplacian laplacian.f90
! or, more generally:
! $ f2py -m laplacian -c laplacian.f90
! To generate the interface use the '-h' option:
! $ f2py -h laplacian.pyf -m laplacian laplacian.f90
! After modifying *.pyf, the new python module can be generated by:
! $ f2py -c laplacian.pyf laplacian.f90

module laplacian

implicit none

contains

    subroutine laplac(arr, lap, m, n)

    integer, intent(in) :: m, n
    integer :: i, j
    double precision, intent(in), dimension(m,n) :: arr
    double precision, intent(out), dimension(m-1,n-1) :: lap
    
    do i = 1, m-1
        do j = 1, n-1
            lap(i,j) = 0.5D0*(arr(i-1,j) + arr(i+1,j) + arr(i,j-1) + arr(i,j+1) - 4.0D0*arr(i,j))
        end do
    end do

    end subroutine laplac    

end module laplacian
